version: "3.9"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "443:443"
    environment:
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}